# Generated by Django 5.0.4 on 2025-07-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_stayintouch_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='area_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
